export const GET_ERRORS = "GET_ERRORS";

// Auth
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Stories Form
export const SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST";
export const FORM_REQUEST_SUBMITTED = "FORM_REQUEST_SUBMITTED";
export const FORM_REQUEST_FAILED = "FORM_REQUEST_FAILED";

// Stories (Display)
export const GETTING_STORIES = "GETTING_STORIES";
export const GOT_STORIES = "GOT_STORIES";
export const FAILED_GETTING_STORIES = "FAILED_GETTING_STORIES";

// Photos
export const POSTING_PHOTOS = "POSTING_PHOTOS";
export const POSTED_PHOTOS = "POSTED_PHOTOS";
export const FAILED_POSTING_PHOTOS = "FAILED_POSTING_PHOTOS";
export const GETTING_PHOTOS = "GETTING_PHOTOS";
export const GOT_PHOTOS = "GOT_PHOTOS";
export const FAILED_GETTING_PHOTOS = "FAILED_GETTING_PHOTOS";

// Weights Form
export const SUBMIT_WEIGHT_REQUEST = "SUBMIT_WEIGHT_REQUEST";
export const WEIGHT_REQUEST_SUBMITTED = "WEIGHT_REQUEST_SUBMITTED";
export const WEIGHT_REQUEST_FAILED = "WEIGHT_REQUEST_FAILED";

// Weights Tracker (Display)
export const GETTING_WEIGHTS = "GETTING_WEIGHTS";
export const GOT_WEIGHTS = "GOT_WEIGHTS";
export const FAILED_GETTING_WEIGHTS = "FAILED_GETTING_WEIGHTS";