export const GET_ERRORS = "GET_ERRORS";

// Auth
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Stories Form
export const SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST";

// Stories
export const GETTING_STORIES = "GETTING_STORIES";
export const GOT_STORIES = "GOT_STORIES";
export const FAILED_GETTING_STORIES = "FAILED_GETTING_STORIES";

// Photos
export const POSTING_PHOTOS = "POSTING_PHOTOS";
export const POSTED_PHOTOS = "POSTED_PHOTOS";
export const FAILED_POSTING_PHOTOS = "FAILED_POSTING_PHOTOS";
export const GETTING_PHOTOS = "GETTING_PHOTOS";
export const GOT_PHOTOS = "GOT_PHOTOS";
export const FAILED_GETTING_PHOTOS = "FAILED_GETTING_PHOTOS";

// Weight
export const SUBMIT_WEIGHT_REQUEST = "SUBMIT_WEIGHT_REQUEST";