export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST";
export const GETTING_STORIES = "GETTING_STORIES";
export const GOT_STORIES = "GOT_STORIES";
export const FAILED_GETTING_STORIES = "FAILED_GETTING_STORIES";
